---
name: Release
on:
  push:
    tags:
      - "v*"
jobs:
  release:
    name: Release
    runs-on: ubuntu-20.04
    steps:
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.20.5
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup make
        run: make all
      - name: Run clean
        run: make clean
      - name: Run netscale
        run: make netscale
      - name: Run container
        run: make container
      - name: Run generate-docker-version
        run: make generate-docker-version
      - name: Run unit test
        run: make test
      - name: Run github-release
        run: make github-release
      - name: Run github-release-built-pkgs
        run: make github-release-built-pkgs
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Release
        uses: goreleaser/goreleaser-action@v4
        with:
          version: v1.9.2
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
