name: leak-test

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: '0'

    - name: Gitleaks
      uses: gitleaks/gitleaks-action@v1.6.0
